
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwijryhqngyzgpgekgek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3aWpyeWhxbmd5emdwZ2VrZ2VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNzM2ODAsImV4cCI6MjA1ODc0OTY4MH0.fO0f3bkEvOFG79AUSz8q5dFzC3zNoAxjli7xyF_xT7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
